Final/SistemaHoteleiro/Visao/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Visao.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            ViewBag.Message = "Seja bem-vindo ao Sistema Hoteleiro.";
            return View();
        }

        public ActionResult Sobre()
        {
            ViewBag.Message = "Conheça tudo sobre o Sistema Hoteleiro.";
            ViewBag.Title = "Sobre";
            return View();
        }

        public ActionResult Autor()
        {
            ViewBag.Message = "Tiago Romero Garcia, a seu dispor.";
            ViewBag.Title = "Autor";
            return View();
        }
    }
}

Final/SistemaHoteleiro/Visao/Controllers/OcupacoesController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Modelo.Dominio;
using Visao.Models;

namespace Visao.Controllers
{
    public class OcupacoesController : Controller
    {
        public ActionResult RegistrarTerminoDeLimpezaDeQuarto()
        {
            ViewBag.Title = "Ocupações";
            ViewBag.Message = "Registrar término de limpeza de quarto.";

            var servicoRelatorio = new ServicoRelatorio.ServicoRelatorioClient();
            var quartos = servicoRelatorio.ObterQuartosEmLimpeza();

            return View(quartos);
        }

        public ActionResult RegistrarLimpo(long id)
        {
            ViewBag.Title = "Ocupações";
            ViewBag.Message = "Registrar término de limpeza de quarto.";

            var servicoOcupacao = new ServicoOcupacao.ServicoOcupacaoClient();
            servicoOcupacao.RegistrarTerminoDeLimpeza(id);

            return RedirectToAction("RegistrarTerminoDeLimpezaDeQuarto");
        }

        public ViewResult ListarCheckIn()
        {
            ViewBag.Title = "Ocupações";
            ViewBag.Message = "Realizar check-in.";

            var servicoReservas = new ServicoReserva.ServicoReservaClient();
            return View(servicoReservas.ObterReservasParaCheckin());
        }

        public ActionResult CheckIn(long id)
        {
            ViewBag.Title = "Ocupações";
            ViewBag.Message = "Realizar check-in.";

            var servicoOcupacao = new ServicoOcupacao.ServicoOcupacaoClient();
            var ocupacao = servicoOcupacao.RegistrarCheckin(id);

            if (ocupacao == null)
            {
                ViewBag.Result = "Não há quartos disponíveis no momento e não foi possível realizar seu checkin.";
            }

            return View(ocupacao);
        }

        public ViewResult ListarCheckOut()
        {
            ViewBag.Title = "Ocupações";
            ViewBag.Message = "Realizar check-out.";

            var servicoOcupacao = new ServicoOcupacao.ServicoOcupacaoClient();
            return View(servicoOcupacao.ObterQuartosOcupados());
        }

        public ActionResult CheckOut(long id)
        {
            var servicoOcupacao = new ServicoOcupacao.ServicoOcupacaoClient();
            var ocupacao = servicoOcupacao.RegistrarCheckout(id);

            return RedirectToAction("Pagar", ocupacao.Conta);
        }

        public ActionResult Pagar(Conta conta)
        {
            ViewBag.Title = "Ocupações";
            ViewBag.Message = "Checkout realizado com sucesso. Pagamento de conta.";

            ViewData["formasDePagamento"] = new SelectList(Enum.GetValues(typeof(FormaDePagamento)));

            return View(conta);
        }

        [HttpPost, ActionName("Pagar")] 
        public ActionResult PagarPost(Conta conta)
        {
            var servicoOcupacao = new ServicoOcupacao.ServicoOcupacaoClient();
            servicoOcupacao.PagarConta(conta);

            return RedirectToAction("ContaPaga");
        }

         public ViewResult ContaPaga()
         {
             ViewBag.Title = "Ocupações";
             ViewBag.Message = "Pagamento de conta.";
             ViewBag.Result = "Conta paga com sucesso.";
             return View();
         }
    }
}

Final/SistemaHoteleiro/Visao/Controllers/RelatoriosController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Modelo.Dominio;
using Visao.Models;

namespace Visao.Controllers
{
    public class RelatoriosController : Controller
    {
        public ActionResult MapaGeralDosQuartos()
        {
            ViewBag.Title = "Relatório";
            ViewBag.Message = "Mapa geral dos quartos.";

            var servicoRelatorio = new ServicoRelatorio.ServicoRelatorioClient();
            var quartos = servicoRelatorio.ObterQuartos();

            return View(quartos);
        }

        public ActionResult QuartosPorCategoria()
        {
            ViewBag.Title = "Relatório";
            ViewBag.Message = "Quartos por categoria.";

            var servicoReserva = new ServicoReserva.ServicoReservaClient();
            var categoriasDeQuarto = servicoReserva.ObterCategoriasDeQuarto();

            return View(categoriasDeQuarto);
        }

        public ActionResult QuartosPorCategoriaPartial(CategoriaDeQuarto categoriaDeQuarto)
        {
            var servicoRelatorio = new ServicoRelatorio.ServicoRelatorioClient();
            var quartos = servicoRelatorio.ObterQuartosPorCategoria(categoriaDeQuarto.Id);

            return View(quartos);
        }

        public ActionResult TodosOsQuartosEmProcessoDeLimpeza()
        {
            ViewBag.Title = "Relatório";
            ViewBag.Message = "Todos os quartos em processo de limpeza.";

            var servicoRelatorio = new ServicoRelatorio.ServicoRelatorioClient();
            var quartos = servicoRelatorio.ObterQuartosEmLimpeza();

            return View(quartos);
        }

        public ActionResult TodosOsQuartosDeUmaDeterminadaCategoria()
        {
            ViewBag.Title = "Relatório";
            ViewBag.Message = "Todos os quartos de uma determinada categoria.";

            var servicoReserva = new ServicoReserva.ServicoReservaClient();
            var categoriasDeQuarto = servicoReserva.ObterCategoriasDeQuarto();

            return View(categoriasDeQuarto);
        }

        public ViewResult TodosOsQuartosDestaCategoria(long id)
        {
            ViewBag.Title = "Relatório";
            ViewBag.Message = "Todos os quartos de uma determinada categoria.";

            var servicoRelatorio = new ServicoRelatorio.ServicoRelatorioClient();
            var quartos = servicoRelatorio.ObterQuartosPorCategoria((long)id);

            return View(quartos);
        }

        public ActionResult QuartosDisponiveisPorPeriodo(PeriodoModel periodo)
        {
            ViewBag.Title = "Relatório";
            ViewBag.Message = "Quartos disponíveis por período.";

            return View(periodo);
        }

        [HttpPost, ActionName("QuartosDisponiveisPorPeriodo")]
        public ActionResult QuartosDisponiveisPorPeriodoPost(PeriodoModel periodo)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Title = "Relatório";
                ViewBag.Message = "Quartos disponíveis por período.";

                if (periodo.DataFim < periodo.DataInicio)
                {
                    ViewBag.Result = "A data inicio deve ser menor que a data fim.";
                    return View(periodo);
                }
                else
                {
                    periodo.DataInicio = periodo.DataInicio.AddHours(12);
                    periodo.DataFim = periodo.DataFim.AddHours(12);

                    var servicoRelatorio = new ServicoRelatorio.ServicoRelatorioClient();
                    var quartos = servicoRelatorio.ObterQuartosDisponiveisPorPeriodo(periodo.DataInicio, periodo.DataFim);

                    periodo.Quartos = new List<Quarto>();

                    foreach (var quarto in quartos)
                    {
                        periodo.Quartos.Add(quarto as Quarto);
                    }

                    return View(periodo);
                }
            }

            return View(periodo);
        }

        public ActionResult FaturamentoDoHotelPorPeriodo()
        {
            ViewBag.Title = "Relatório";
            ViewBag.Message = "Faturamento do hotel por período.";

            return View();
        }

        [HttpPost]
        public ActionResult FaturamentoDoHotelPorPeriodo(PeriodoModel periodo)
        {
                if (periodo.DataFim < periodo.DataInicio)
                {
                    ViewBag.Title = "Relatório";
                    ViewBag.Message = "Faturamento do hotel por período.";
                    ViewBag.Result = "A data inicio deve ser menor que a data fim.";
                    return View(periodo);
                }
                else
                {
                    periodo.DataInicio = periodo.DataInicio.AddHours(12);
                    periodo.DataFim = periodo.DataFim.AddHours(12);

                    var servicoRelatorio = new ServicoRelatorio.ServicoRelatorioClient();
                    periodo.Faturamento = servicoRelatorio.ObterFaturamentoPorPeriodo(periodo.DataInicio, periodo.DataFim);

                    return RedirectToAction("ExibirFaturamentoDoHotelPorPeriodo", periodo);
                }

            return View(periodo);
        }

        public ActionResult ExibirFaturamentoDoHotelPorPeriodo(PeriodoModel periodo)
        {
            ViewBag.Title = "Relatório";
            ViewBag.Message = "Faturamento do hotel por período.";

            return View(periodo);
        }

    }
}

Final/SistemaHoteleiro/Visao/Views/Home/Autor.cshtml
<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<p>Sou Tiago Romero Garcia, 27 anos, casado, nasci em São Paulo (SP), hoje moro em Santa Luzia (MG).</p>
<p>Sou Gerente de Engenharia e Líder de equipe na Avenue Code no Brasil, em Belo Horizonte (MG), além de Engenheiro de Software especializado em Java e UI com 5 anos de experiência, e já trabalhei com desenvolvimento de software para e-commerce, sistemas ERP, redes sociais e comunicação com Smart Cards.</p>
<p>Graduei em Janeiro em 2009 em Ciência da Computação na UNIFEI, em Itajubá (MG). Desenvolvi trabalhos acadêmicos nas áreas de Estruturas de Dados, Algoritmos de Classificação e Pesquisa de Dados, Análise de Algoritmos, Computação Ubíqua e Engenharia de Software. Meu trabalho de conclusão de curso abordou Arquiteturas Orientadas a Serviço (SOA).</p>
<p>Desde Setembro de 2011 estou cursando especialização em Arquitetura de Sistemas Distribuídos na PUC Minas, câmpus São Gabriel, em Belo Horizonte (MG).</p>
<p>Possuo as certificações:</p>
<ul>
    <li>Oracle Certified Professional, Java EE 5 Web Component Developer</li>
    <li>Oracle Certified Professional, Java Programmer 5</li>
    <li>First Certificate of English (FCE)</li>
</ul>
<p>Sites:</p>
<ul>
    <li>Meu site pessoal - <a href="http://www.tgarcia.com.br/" target="_blank">www.tgarcia.com.br</a></li>
    <li>Meu blog - <a href="http://blog.pt.tgarcia.com.br/" target="_blank">blog.pt.tgarcia.com.br</a></li>
    <li>Meu currículo - <a href="http://www.tgarcia.com.br/curriculo" target="_blank">www.tgarcia.com.br/curriculo</a></li>
    <li>Sagas de Cíntia e Tiago - <a href="http://sagasdecintiago.wordpress.com/" target="_blank">sagasdecintiago.wordpress.com</a></li>
</ul>
<p>Contato: <a href="mailto:contato@tgarcia.com.br">contato@tgarcia.com.br</a> ou <a href="http://www.tgarcia.com.br/contato" target="_blank">www.tgarcia.com.br/contato</a></p>

Final/SistemaHoteleiro/Visao/Views/Home/Index.cshtml
@section featured {
<section class="featured">
    <div class="content-wrapper">
        <hgroup class="title">
            <h1>@ViewBag.Title.</h1>
            <h2>@ViewBag.Message</h2>
        </hgroup>
    </div>
</section>
}

@if (Request.IsAuthenticated)
{
<section class="features">
    <h2>Menu de opções:</h2>
    <section class="feature">
        <h3>Reservas</h3>
        <ul>
            <li>@Html.ActionLink("Cadastro de clientes", "Index", "Clientes")</li>
            <li>@Html.ActionLink("Cadastro de reservas", "Index", "Reservas")</li>
        </ul>
    </section>
    <section class="feature">
        <h3>Ocupações</h3>
        <ul>
            <li>@Html.ActionLink("Registrar check-in", "ListarCheckIn", "Ocupacoes")</li>
            <li>@Html.ActionLink("Registrar check-out", "ListarCheckOut", "Ocupacoes")</li>
            <li>@Html.ActionLink("Registrar término de limpeza de quarto", "RegistrarTerminoDeLimpezaDeQuarto", "Ocupacoes")</li>
        </ul>
    </section>
    <section class="feature">
        <h3>Relatórios</h3>
        <ul>
            <li>@Html.ActionLink("Quartos por categoria", "QuartosPorCategoria", "Relatorios")</li>
            <li>@Html.ActionLink("Quartos disponíveis por período", "QuartosDisponiveisPorPeriodo", "Relatorios")</li>
            <li>@Html.ActionLink("Faturamento do hotel por período", "FaturamentoDoHotelPorPeriodo", "Relatorios")</li>
            <li>@Html.ActionLink("Quartos de uma determinada categoria", "TodosOsQuartosDeUmaDeterminadaCategoria", "Relatorios")</li>
            <li>@Html.ActionLink("Quartos em processo de limpeza", "TodosOsQuartosEmProcessoDeLimpeza", "Relatorios")</li>
            <li>@Html.ActionLink("Mapa geral dos quartos", "MapaGeralDosQuartos", "Relatorios")</li>
        </ul>
    </section>
</section>
}
else
{
        <p>
            Este é um sistema restrito ao uso da recepção do hotel. Para acessar sua conta, gentileza clicar na caixa cinza escrito <b>Acessar sua conta</b> no canto superior direito desta página.
        </p>
}

Final/SistemaHoteleiro/Visao/Views/Home/Sobre.cshtml
<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<h3>Contextualização</h3>
<p><b>Sistema Hoteleiro</b> é o meu trabalho final da disciplina <b>Arquitetura de Aplicativos Ambiente .NET</b> da 4a turma do curso de pós-graduação de especialização em <a href="http://www.pucminas.br/cursos/dados_cursos.php?tipo=2&instituto=403010000&pai=339&pagina=747&menu=943&cabecalho=14&lateral=18&situacao=201201&curso=2809" target="_blank">Arquitetura de Sistemas Distribuídos</a> oferecido pelo <a href="http://www.pucminas.br/iec" target="_blank">Instituto de Educação Continuada</a> da <a href="http://www.pucminas.br" target="_blank">Pontifícia Universidade Católica de Minas Gerais</a> na unidade <a href="http://www.pucminas.br/destaques/unidades.php?unidade=204000000&pagina=888" target="_blank">São Gabriel</a>.</p>
<h3>Sistema 28: Sistema hoteleiro</h3>
<p>Deseja-se desenvolver um sistema para um hotel que atenda aos seguintes requisitos:</p>
<ul>
    <li>O hotel possui diferentes quartos que são classificados em uma das seguintes categorias: Presidencial, Econômica, Simples, Duplo ou Triplo. O valor base da diária dos quartos depende da categoria do quarto.</li>
    <li>Quando o cliente telefona ou vem até o hotel e pede para reservar um quarto, a recepção verifica se existe quarto disponível no período solicitado. Caso positivo, o cliente é cadastrado e é feita a reserva do quarto. Caso negativo, o cliente é informado da não disponibilidade do quarto.</li>
    <li>Quando o cliente não mais desejar o quarto reservado o funcionário providencia o cancelamento da reserva, disponibilizando novamente o quarto.</li>
    <li>Quando o cliente ocupar um quarto reservado previamente, caracteriza-se uma ocupação do quarto.</li>
    <li>Quando o cliente deixar o hotel será fornecida a respectiva conta e o quarto estará disponível para limpeza.</li>
    <li>Quando o quarto estiver limpo a recepção do hotel torna-o disponível.</li>
    <li>O cliente pode pagar a conta à vista, cheque ou usando cartão de crédito. Dados sobre a conta são importantes serem armazenados como a forma de pagamento, valor da hospedagem, total do frigobar.</li>
</ul>
<p>Relatórios:</p>
<ul>
    <li>Quartos por categoria</li>
    <li>Quartos disponíveis por período</li>
    <li>Faturamento do hotel por período</li>
    <li>Todos os quartos de uma determinada categoria</li>
    <li>Todos os quartos em processo de limpeza</li>
    <li>Mapa geral dos quartos (ocupados, livres, em limpeza)</li>
</ul>
<h3>Tecnologias escolhidas</h3>
<p>O sistema foi desenvolvido na plataforma .NET com as seguintes tecnologias:</p>
<ul>
    <li>Camada de visão em ASP.NET MVC 4 com Razor</li>
    <li>Camada de negócio desenvolvida em C# e exportada como serviços WCF</li>
    <li>Camada de persistência desenvolvida em C# e mapeada em NHibernate</li>
    <li>Banco de dados SQL Server 2008 R2</li>
</ul>
<h3>Modelagem</h3>
<p>Diagrama de casos de uso:</p>
<img src="/Images/CasosDeUso.png" width="960" />
<p>Diagrama de classes:</p>
<img src="/Images/Classes.png" width="960" />